"""add username

Revision ID: 756db3cd4c73
Revises: 80091d8ea4f9
Create Date: 2024-11-09 22:26:07.258764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756db3cd4c73'
down_revision: Union[str, None] = '80091d8ea4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_telegram_id_key', 'users', type_='unique')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_telegram_id_key', 'users', ['telegram_id'])
    # ### end Alembic commands ###
